---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: vm1
  labels:
    app: foo
spec:
  address: 2001:db8:1234:5678:8:2:4f:a005
  labels:
    app: foo
  serviceAccount: default

